# Generated by Django 3.0.8 on 2020-07-11 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200710_2314'),
        ('accounts', '0004_customer_user'),
    ]

    operations = [
    ]
